### ISSUE TITLE
On SQL Error (plv8.execute("erroneous sql")) it's returns Error 0 and SQLState XX000

### ISSUE THREAD

**Issue by alexandru-lazarev** [plv8/plv8#160] opened 2016-03-03 22:17 UTC
It seems that on any SQL Error (invalid syntax, invalid column name in select, deadlock, connection dropped, etc) plv8 returns proper error textual description but error code is always 0 and SQLState is XX000.

Additional info: Checked it within Java+SpringBoot+Hibernate project, where on some actions are triggered PostgreSQL SPs written in plv8.

plv8 1.4.4, plv8 1.5.0

**Comment by JerrySievert** [comment] 2016-03-03 22:25
do you have a simple test case that exposes this, as well as what is expected?  that will give me a quick way to both figure out the error, as well as provide a regression test.

thanks!

**Comment by alexandru-lazarev** [comment] 2016-03-03 22:39
I have a simple db for test, table foo (id int, value num). 
There are 2 methods causing (forcibly) deadlock: 
```
CREATE OR REPLACE FUNCTION public.foo81()
  RETURNS bigint AS
$BODY$
function sleep( sleepDuration ){
    var now = new Date().getTime();
    while(new Date().getTime() < now + sleepDuration){ /* do nothing */ } 
}

plv8.elog(NOTICE, "Update foo 1");
plv8.execute("update foo set value = value+1 where id = 1");
plv8.elog(NOTICE, "sleep 10 sec");
sleep(10000);
plv8.elog(NOTICE, "Update foo 2");
plv8.execute("update foo set value = value+1 where id = 2");

plv8.elog(NOTICE, "returning result");
var res = plv8.execute("select count(*) as count from foo");
plv8.elog(NOTICE, "result = " + res[0].count);
return res[0].count;
$BODY$
  LANGUAGE plv8 VOLATILE
  COST 100;
ALTER FUNCTION public.foo81()
  OWNER TO postgres;
```

And foo82() doing same, but updates in reverse order. If I call them in parallel from Java (JDBC) I receive org.postgresql.util.PSQLException with SQLState XX000 and Error Code 0. 
If rewrite methods in pl/pgsql then propper exception code and SQL State is returned "40P01" (link: http://www.postgresql.org/docs/current/static/errcodes-appendix.html)

Moreover, even there might be incorrect column name in sql statement, and JDBC anyway will return PSQLException with SQLState XX000 and Error Code 0, even if description is OK, but to rely on textual description in exception handling is bad-bad practice.

Thanks, let me know if I need provide more info.

**Comment by JerrySievert** [comment] 2016-03-04 01:42
thanks much, this should be enough for me to be able to reproduce the error.

unfortunately, i am traveling at the moment, so the soonest i personally will be able to start looking for a solution will be this weekend (i can try for sunday) - unless someone else is willing to take a look and try to fix it.

**Comment by alexandru-lazarev** [comment] 2016-03-04 07:51
@JerrySievert, anyway I will add a little bit more info.
Just checked it without Java project, I did it prom `psql` transactions. 
There result is the same for plv8 methods - error XX000. Below is snapshot from log: 
```
ERROR:  XX000: deadlock detected
DETAIL:  foo82() LINE 12: plv8.execute("update foo set value = value+1 where id = 1");
LOCATION:  rethrow, plv8.cc:1768
STATEMENT:  select foo82();
```

Then I rewrote SPs in pl/pgsql:
```
CREATE OR REPLACE FUNCTION public.foo1()
  RETURNS bigint AS
$BODY$begin
raise notice 'Update foo 1';
execute 'update foo set value = value+1 where id = 1';
raise notice 'sleep 10 sec';
perform pg_sleep(10);
raise notice 'Update foo 2';
execute 'update foo set value = value+1 where id = 2';
return (select count(*) from foo);
end$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION public.foo1()
  OWNER TO postgres;
```
And SP `foo2()` doing exactly the same, but updates are in reverse order.

Here I receive same error, but with properly defined error code (SQLState). Log Snapshot below.
```
ERROR:  40P01: deadlock detected
DETAIL:  Process 4748 waits for ShareLock on transaction 1884; blocked by process 4745.
        Process 4745 waits for ShareLock on transaction 1885; blocked by process 4748.
        Process 4748: select foo1();
        Process 4745: select foo2();
HINT:  See server log for query details.
CONTEXT:  while updating tuple (0,27) in relation "foo"
        SQL statement "update foo set value = value+1 where id = 2"
        PL/pgSQL function foo1() line 7 at EXECUTE
LOCATION:  DeadLockReport, deadlock.c:956
STATEMENT:  select foo1();
```


Regards,
AlexL

**Comment by JerrySievert** [comment] 2016-03-27 21:29
i know where the issue lies with this, but will need to find some dedicated time to fix it.

**Comment by alexandru-lazarev** [comment] 2016-04-05 07:25
Hi @JerrySievert, sorry for insistence, any updates on this issue?

**Comment by JerrySievert** [comment] 2016-04-06 01:58
Still trying to find time. I've only had about 2 days without travel in the last weeks, trying to find the time to dive in.

**Comment by alexandru-lazarev** [comment] 2016-10-04 19:39
@JerrySievert 
Is there at least workaround for this issue?
As example - could I do similar to PL/pgSQL "RAISE SQLSTATE 40P01" in plv8?

Thanks

**Comment by JerrySievert** [comment] 2017-07-02 21:36
this isn't actually fixed by #227, what's missing is a comprehensive mapping of v8 errors to postgres errors - these are typically generated form `errcodes.h` or `errcodes.txt`.

**Comment by bendiy** [comment] 2017-07-03 22:53
#227 should fix any PostgreSQL or plpgsql errors. If you generate an error in JavaScript, the error state is still `XX000`:
```
do language plv8 $$
throw new Error('foo');
$$;
```
```
ERROR:  foo
CONTEXT:  undefined() LINE 2: throw new Error('foo');
********** Error **********

ERROR: foo
SQL state: XX000
Context: undefined() LINE 2: throw new Error('foo');
```
We need to map JavaScript/V8 errors to these codes:
https://github.com/postgres/postgres/blob/3217327053638085d24dd4d276e7c1f7ac2c4c6b/src/backend/utils/errcodes.txt
Or add new ones?

**Comment by JerrySievert** [comment] 2017-07-03 22:56
unfortunately, errors coming through `pg_error` don't seem to be keeping the error state when `PG_RE_THROW()` is executed.

and it looks like `int32_t code = errCode->Int32Value();` also isn't mapping an error code (I spent a while looking at this yesterday).

**Comment by alexandru-lazarev** [comment] 2017-07-04 06:09
Hi All, 
thanks everybody (cc: @JerrySievert , @bendiy ) for feedback - i was waiting long time for this solution for long time. 
I have a QUESTION - For which plv8 release is this fix scheduled? (Will be it included in 1.4.X and 1.5.X as well?)

Regards,
AlexL

**Comment by JerrySievert** [comment] 2017-07-04 06:12
reopening because I don't think it's 100% fixed yet, but will continue looking at it in the next day or so.

this will likely not be backported to 1.4 or 1.5, as those are critical bug fixes only, and this has been working as designed - we're looking at modifying the behavior completely, which was one of my reasons for a 2.1 release instead of even releasing under the 2.0 branch.

do you mind if I ask what is stopping you from using 2.0?

**Comment by alexandru-lazarev** [comment] 2017-07-04 06:24
@JerrySievert , Thanks for feedback. 
Wit respect to "do you mind if I ask what is stopping you from using 2.0?" - actually we are using plv8 v1.4.X with PG 9.5-9.6 on CentOS 6.5-6.7. 
I remember there were some tricks to compile plv8 1.5.X on CentOS 6.7 because v8 was requiring some newer GCC and other stuff versions, which were tricky to configure under CentOS 6.7.

I'll wait for new release (2.X) and try compile & install and test my use cases and update you on results.

Regards,
AlexL

**Closed** 2023-06-27 03:55 UTC

**Comment by alexandru-lazarev** [comment] 2023-06-27 07:16
Thanks :)
