### ISSUE TITLE
Release Static Builds

### ISSUE THREAD

**Issue by bendiy** [plv8/plv8#220] opened 2017-04-25 15:40 UTC
@JerrySievert 

I wanted to check with you about the possibility of adding support for static builds of PL/v8 to future releases. At @xtuple, we were discussing how nice the EnterpriseDB PostgreSQL installers are. They're an easy way for end users to get a PostgreSQL server up and running. The installer also includes a lot of the basic extensions someone might need. We reached out to @dpage at @EnterpriseDB about why they don't include PL/v8 in their installer. He mentioned that the build process for PL/v8 had been difficult in the past.

I think one way to get over the hurdle of the build process is to include static build of PL/v8 with each release. This is similar to how Node.js ships with a static libv8 build. By including a static build with each release, we could remove the need for libv8 to be present on the machine. You are aware of the old libv8 version on the debain OSs and how that has forced you to maintain the 1.4.x branch of PL/v8.

We're already maintaining a set of static PL/v8 builds at xTuple. You can find them here:
- http://updates.xtuple.com/updates/plv8/linux32/xtuple_plv8.tgz
- http://updates.xtuple.com/updates/plv8/linux64/xtuple_plv8.tgz
- http://updates.xtuple.com/updates/plv8/mac/xtuple_plv8.tgz
- http://updates.xtuple.com/updates/plv8/win/xtuple_plv8.zip

They currently are built with PL/v8 version 1.4.4, but just last week we started the process of moving them to 2.0.3. The builds are created by a script that does a PL/v8 static build for `PGVERSIONS="9.1.2 9.2.10 9.3.2 9.4.4 9.5.0"`. We'll be adding 9.6.x soon.

Instead of maintaining these scripts at xTuple, I'd like to work with you on contributing them to the PL/v8 repo and start to use them to publish static builds with each release. I believe the package repository maintainers could then pick them up as official releases and remove the need for a dynamic libv8 build.

Thoughts?

**Comment by JerrySievert** [comment] 2017-04-25 16:28
just making sure you know about `make static`

I'm guessing that the support with enterprisedb is due to them needing to support windows, where building v8 can be ... challenging.  unfortunately, there's not much I can do about that, just specify versions that can work.

**Comment by JerrySievert** [comment] 2017-04-25 16:55
on the OS maintainers: none of the linux distro maintainers that I've discussed with will release static binaries, which is one of the biggest reasons why debian/ubuntu are so far behind - trying to support v8.

**Comment by bendiy** [comment] 2017-04-25 17:25
Yes, we are using `make static` and do have Windows builds working. By releasing static builds, end users could avoid needing to build it themselves.

Looking at what Node.js is doing, `... | bash` aside, the scripts are adding `nodesource.com` to `/etc/apt/sources.list.d`:
- https://nodejs.org/en/download/package-manager/

This would be similar to using pgdg as the source to install PL/v8, but distributing static builds:
- http://apt.postgresql.org/pub/repos/apt/pool/main/p/plv8/

Do you know where to check on the status of a newer libv8 in debian? I found the link once a few months ago, but can't seem to dig it up.

Our end goal is to make it easier to distribute and install PL/v8 on all of the popular OSs. Maybe there's another way to accomplish that.

**Comment by JerrySievert** [comment] 2017-04-25 17:30
I check on the libv8 status on a fairly regular basis.  @christophberg is our friendly neighborhood Debian maintainer.

**Comment by ChristophBerg** [comment] 2017-05-01 16:09
@JerrySievert was right in saying that statically linking v8 is a no-go on Debian. This would defeat the idea of shipping libs in separately-updateable packages for maintainability and security (update) reasons. 

The problem with v8 in Debian is that it is being maintained by the Javascript team which is understaffed and not keeping up with packaging new v8 versions. I'm merely the plv8 maintainer, and with already too many packages on my plate, I'd rather not step up to maintain v8 itself. (So, even if I chose to ignore the first point above, I'd rather not add "update v8" to the task list for maintaining the plv8 packages.)

v8 in Debian: https://packages.qa.debian.org/libv/libv8-3.14.html

**Comment by JerrySievert** [comment] 2017-05-01 20:45
Thanks for weighing in @ChristophBerg, I appreciate it.

@bendiy my biggest concerns about releasing binaries across multiple distributions outside of the maintainers are as follows:

I no longer have access to a full lab to build and validate releases.  I have a lab at home, but it is mostly focused on IoT, supporting devices for it, and my personal cloud infrastructure.  while I have some devoted to development and support of plv8, most of it is on-demand, and a bit taxing on what I have.  unfortunately, my cash situation (not working for the time being) does not allow me to easily change this at this time.

I'm concerned about the time requirements to support these releases across platforms, this is a pretty big commitment, as @ChristophBerg will tell you, and multiplying across multiple platforms makes this a lot more difficult.  I am a single person on this project, and have other commitments as well.

There is currently no infrastructure in place to do distribution.  I can build this, but it will take time.  I look at PostGIS as a good model for this.  (they mostly rely on the Postgres repos)


All of that said, I'm spending some time investigating what it would take - I've spent some time with a friend at RedHat who has a lot more excess computing platform (personally) than I do, and am happy to reach out to @joemccann and @dshaw (hi Joe! hi Dan! long time no see!) at Nodesource to see how they are handling the releases and validation of NodeJS (can you guys help?)

In the mean time, I'm open to suggestions.

**Comment by joemccann** [comment] 2017-05-02 00:02
Feel free to email me joe@nodesource.com

**Comment by JerrySievert** [comment] 2017-05-02 20:07
@joemccann sent, thanks.

**Comment by bendiy** [comment] 2017-05-09 20:56
Thanks everyone for your comments.

I discussed this with the team at xTuple last week and we're planning to start by committing some resources to port our static build scripts over to the PL/v8 repo. That should make it easy to build a static release for linux, MacOS and Windows. I can't commit to any timeline on that just yet. Once done, we can look at what server resources are needed to support testing and building releases for those OSs during the release process.

**Comment by JerrySievert** [comment] 2017-05-09 23:27
my preference would be a separate repo, which is the same methodology that Nodesource is using: https://github.com/nodesource/distributions

I can create the repo when needed.

**Comment by bendiy** [comment] 2017-07-19 14:05
Related:
https://github.com/plv8/plv8/issues/200#issuecomment-315543497

Instructions to build V8 on Windows, which will be needed to support static releases.

**Comment by robe2** [comment] 2018-10-20 22:01
@bendiy I see you have plv8 2.3.2 now for Windows for PostgreSQL 10.  I haven't had a chance to test it but I confirmed it installed fine on my EDB 10 windows 64-bit.  Any plans to provide one for PostgreSQL 11 which just got released?

**Comment by JerrySievert** [comment] 2018-10-20 22:06
@robe2 it should now build out of the box as long as you have the [build requirements](https://plv8.github.io/#building-for-windows).

there is an issue in regards to pg11 and enabling of jit that I need to patch in, but otherwise it should build with no issue.

be warned that those build requirements will change to include msvc 2017 (community edition works) when plv8 3.0 is released, as v8's build requirements have changed for newer releases.

**Comment by robe2** [comment] 2018-10-20 23:03
It seems like the Cmake setup was changed to also download v8 and compile it is that right? Wasn't clear from the instructions as it mentioned doing a bootstrap first.

I'll try later once I clear some disk space on my computer.

**Comment by JerrySievert** [comment] 2018-10-20 23:08
yes, but once it is downloaded it *should* continue to build without re-downloading.  and yes, it's quite the large repo and toolchain.

**Comment by robe2** [comment] 2018-10-21 19:10
@JerrySievert  sadly that didn't work too well even after I cleared disk space.  It just kept on getting hung on

`Downloading 1 files took 6.042000 second(s)
Running hooks:  71% (23/32) win_toolchain
`

I left it sitting there for 8 hrs and didn't change, so I presume there is some hidden prompt waiting for something as it seemed to launch 5 git processes and one git-remote-https.  This was trying with VS 2015 (which I think is what EDB is using for their PostgreSQL 11 and 10).  At anyrate using VS to build things is not my ideal for building since it stuffs in a VS runtime that I'd feel obliged to keep in synch with whatever EDB is using to build with.  That said I still prefer mingw64 for building windows stuff, and will try and see if I can get further on that.

**Comment by JerrySievert** [comment] 2018-10-22 15:20
you're running into an issue in v8 itself, it downloads its own toolchain regardless of platform, and what compiler used to compile plv8.

you should be able to take a look either in `bootstrap.bat` or in `Makefile` at the root and see what's it's doing:

```
fetch v8
gclient sync
tools/v8_gen.py
ninja
```

plv8 itself builds like a normal pg extension (except for being c++)

adding `-vv` as an argument to any of the v8 python scripts will show you what it's doing and where it's failing, it's usually easier to figure out from there.

**Comment by robe2** [comment] 2018-12-05 17:40
@davidbeauchamp  Thanks a bunch works great so far.  No I haven't had a chance to work thru the build process again.

**Comment by robe2** [comment] 2018-12-08 22:40
@davidbeauchamp  I did discover a small little bug.  At first I thought it was an issue with pgAdmin4 (and couldn't remember if I ever saw the extensions list in pg11).  Then I decided this time to browse the extensions in pgAdmin 3, and it too couldn't list the extensions tree after copying over the plv8 files.

The issue was the encoding of the plcoffee.control and plls.control files - they were encoded as UCS-2 BE BOM  so when the extensions query in pgAdmin went to inspect them, it would throw an error "Syntax error" in line1.

I resaved the control files in Notepad++ as UTF-8 and then it was fine.  The plv8.control file was fine which is why I didn't noticed the issue when I installed plv8 in my database.

**Comment by JerrySievert** [comment] 2018-12-10 03:40
@robe that's interesting - the 3 control files should be built using the same script:

```
get-content plv8.control.common | %{$_ -replace "@LANG_NAME@","JavaScript"} | %{$_ -replace "@PLV8_VERSION@",$version} | out-file -filepath plv8.control
get-content plv8.control.common | %{$_ -replace "@LANG_NAME@","CoffeeScript"} | %{$_ -replace "@PLV8_VERSION@",$version} | out-file -filepath plcoffee.control
get-content plv8.control.common | %{$_ -replace "@LANG_NAME@","LiveScript"} | %{$_ -replace "@PLV8_VERSION@",$version} | out-file -filepath plls.control
```

maybe @davidbeauchamp can comment on whether or not his build is using the script for generation?  otherwise, I'm at a loss.

likely, these 2 extensions will be disabled by default in 3.0.

**Comment by JerrySievert** [comment] 2018-12-10 05:06
@bendiy @davidbeauchamp would you both be willing to take a look at `r3.0alpha` (now the default branch) and see how it works for you as a windows build?

this will help get plv8 closer to a 3.0 release.

**Comment by davidbeauchamp** [comment] 2018-12-10 14:04
@JerrySievert Sure thing. I can do that in that evening tomorrow. Regarding the encoding of the .control files, I am using the provided script for generating the extra files and they should all be encoded the same way. Once I build tomorrow I will look at the resulting files and see how they come out.

**Comment by JerrySievert** [comment] 2018-12-10 18:17
thanks David!  regarding the control files, I could understand if *all* of them had the same encoding, but just 2 of the 3 is weird.

**Comment by davidbeauchamp** [comment] 2018-12-13 02:23
@JerrySievert Unfortunately I cannot build v8 `7.0.276.20`, thanks to the inability to complete the build file generate step. 

https://groups.google.com/d/msg/v8-users/u17aMkTzErk/ud9WyqbTCgAJ acknowledges the inability to build on windows, but falsely claims the normal `gn` method will work. Currently none of the methods [here](https://v8.dev/docs/build-gn) work on Windows.

I haven't tried any other tags in 7.0.x, I am not sure which direction you want to go there (I vaguely remember previous conversation about staying in line with nodejs..). Otherwise I'll try to watch for a v8 build that works on Windows..

**Comment by JerrySievert** [comment] 2018-12-13 02:54
hm. that's what I was afraid of, the same issue I ran into over a month ago but I was hoping it was something to do with my bad internet access or environment (the build requirements changed)

I'm happy to go up if we can find a version it works on - it's not released as of yet, and the push to match node was to try to share a v8, which is not really possible anymore.

**Comment by JerrySievert** [comment] 2018-12-13 20:16
@davidbeauchamp as an aside, this is what error I receive:

```
________ running 'C:\Python27\python.exe v8/build/vs_toolchain.py update' in 'C:\msys64\tmp\work\plv8\windows\vendor'



Please follow the instructions at https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md


Traceback (most recent call last):
  File "v8/build/vs_toolchain.py", line 468, in <module>
    sys.exit(main())
  File "v8/build/vs_toolchain.py", line 464, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "v8/build/vs_toolchain.py", line 410, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\msys64\\tmp\\work\\plv8\\windows\\vendor\\v8\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\msys64\\tmp\\work\\plv8\\windows\\vendor\\v8\\build\\win_toolchain.json', '3bc0ec615cf20ee342f3bc29bc991b5ad66d8d2c']' returned non-zero exit status 1
Error: Command 'C:\\Python27\\python.exe v8/build/vs_toolchain.py update' returned non-zero exit status 1 in C:\msys64\tmp\work\plv8\windows\vendor
Hook ''C:\Python27\python.exe' v8/build/vs_toolchain.py update' took 12.54 secs
PS C:\msys64\tmp\work\plv8\windows\vendor\v8> gn gen out\x64.release
Traceback (most recent call last):
  File "C:/msys64/tmp/work/plv8/windows/vendor/v8/build/vs_toolchain.py", line 468, in <module>
    sys.exit(main())
  File "C:/msys64/tmp/work/plv8/windows/vendor/v8/build/vs_toolchain.py", line 464, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "C:/msys64/tmp/work/plv8/windows/vendor/v8/build/vs_toolchain.py", line 439, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
  File "C:/msys64/tmp/work/plv8/windows/vendor/v8/build/vs_toolchain.py", line 42, in SetEnvironmentAndGetRuntimeDllDirs
    update_result = Update()
  File "C:/msys64/tmp/work/plv8/windows/vendor/v8/build/vs_toolchain.py", line 410, in Update
    subprocess.check_call(get_toolchain_args)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\msys64\\tmp\\work\\plv8\\windows\\vendor\\v8\\third_party\\depot_tools\\win_toolchain\\get_toolchain_if_necessary.py', '--output-json', 'C:\\msys64\\tmp\\work\\plv8\\windows\\vendor\\v8\\build\\win_toolchain.json', '3bc0ec615cf20ee342f3bc29bc991b5ad66d8d2c']' returned non-zero exit status 1
```

as far as I can tell, I'm up to date on the requirements, but this being windows it's hard to tell.

**Comment by davidbeauchamp** [comment] 2018-12-13 20:33
This is the same error I was getting, with all of the generation methods (gn, gm.py, v8gen.py...yeah). I tried to fake it out by using the generated files from my previous successful build but it was too smart and tried to regenerate them anyways, and failed with this message each time. I didn't dig too much into figuring out what changed, however I was going to look for later tags than the one in `bootstrap.bat` to see if anything has been fixed. Depending on how things go that may be tonight, tomorrow night if not.

**Comment by JerrySievert** [comment] 2019-03-20 00:52
`7.0.302` is building cleanly on all platforms for me, including windows.  I've made several other improvements to 3.0alpha in the last week as well. I'll likely push up a change to `7.0.302` as well.

**Comment by JerrySievert** [comment] 2019-03-20 03:08
I'm going to close this issue, as it is way off of its original topic.

also, going to open a new PR with the updated windows build for 7.0.302.

**Closed** 2019-03-20 03:08 UTC

**Comment by ikalafat** [comment] 2019-08-27 09:49
Hey @bendiy 

Apologies for "jumping into" the thread, there aren't much references to your (xtuple) PLv8 builds here.

I've installed PG11.5 on Windows machine, however, I've encountered problem when using your build (http://updates.xtuple.com/updates/plv8/win/xtuple_plv8.zip)

I got error when running 
`CREATE EXTENSION IF NOT EXISTS plv8`

Error was
```
ERROR:  syntax error at or near "#"
LINE 1: CREATE EXTENSION IF NOT EXISTS plv8
```

I've traced the error up to `plv8-2.3.11.sql` file. Obviously, PostgreSQL is getting confused with preprocessor directives such as 

```
#include "pg_config.h"
#if PG_VERSION_NUM < 90100
...
```

Eventually, I've cleaned the file to leave only this

```
CREATE FUNCTION plv8_call_handler() RETURNS language_handler
 AS 'MODULE_PATHNAME' LANGUAGE C;
CREATE FUNCTION plv8_inline_handler(internal) RETURNS void
 AS 'MODULE_PATHNAME' LANGUAGE C;
CREATE FUNCTION plv8_call_validator(oid) RETURNS void
 AS 'MODULE_PATHNAME' LANGUAGE C;
CREATE TRUSTED LANGUAGE plv8
 HANDLER plv8_call_handler
 INLINE plv8_inline_handler
 VALIDATOR plv8_call_validator;
CREATE DOMAIN plv8_int2array AS int2[];
CREATE DOMAIN plv8_int4array AS int4[];
CREATE DOMAIN plv8_float4array AS float4[];
CREATE DOMAIN plv8_float8array AS float8[];


CREATE OR REPLACE FUNCTION plv8_version ( )
RETURNS TEXT AS
$$
	return "2.3.11";
$$ LANGUAGE plv8;
```

And Creating the extension went through. 

Is this correct way to go? I'm not sure will I encounter any issues in the future. 

Thanks!

**Comment by ikalafat** [comment] 2019-11-13 09:39
Just a quick follow-up on my previous comment. 

It seems that with the newer version of xtuple_plv8.zip (which can be downloaded from same link), the file I had problems with no longer contains the preprocessor directives. 

A side note, some files still have weird encoding (UCS-2 if I recall correctly), and they need to be modified to UTF8 for a successful install. 

Cheers.
