### ISSUE TITLE
Possible to install on OS X using Homebrew?

### ISSUE THREAD

**Issue by brucepom** [plv8/plv8#212] opened 2017-02-27 17:48 UTC
Hey guys, just wondering if this is available via Homebrew. I'm running OS X El Capitan (10.11.5). And trying to install using Homebrew yields the following:
```
$ brew install plv8
Error: No available formula with the name "plv8" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```
I'd really appreciate any input on this. Thanks so much!

**Comment by tjwebb** [comment] 2017-03-19 02:17
This approach should work on most platforms: https://github.com/langateam/node-plv8#plv8-extension

**Comment by cupuyc** [comment] 2017-09-19 12:21
Suggested workaround with `pgxnclient install plv8` doesn't work for me :-(

```
➜  dir git:(develop) ✗ sudo easy_install pgxnclient
Password:
Searching for pgxnclient
Best match: pgxnclient 1.2.1
Processing pgxnclient-1.2.1-py2.7.egg
pgxnclient 1.2.1 is already the active version in easy-install.pth
Installing pgxn script to /usr/local/bin
Installing pgxnclient script to /usr/local/bin

Using /Library/Python/2.7/site-packages/pgxnclient-1.2.1-py2.7.egg
Processing dependencies for pgxnclient
Finished processing dependencies for pgxnclient
➜  dir git:(develop) ✗ sudo pgxnclient install plv8
INFO: best version: plv8 2.1.0
INFO: saving /tmp/tmpBmnrZa/plv8-2.1.0.zip
INFO: unpacking: /tmp/tmpBmnrZa/plv8-2.1.0.zip
INFO: building extension
sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "2.1.0"/' plv8_config.h.in > plv8_config.h
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/local/Cellar/postgresql/9.6.2/include/server -I/usr/local/Cellar/postgresql/9.6.2/include/internal -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/libxml2  -fPIC -c -o plv8.o plv8.cc
In file included from plv8.cc:8:
./plv8.h:12:10: fatal error: 'v8.h' file not found
#include <v8.h>
         ^
1 error generated.
make: *** [plv8.o] Error 1
ERROR: command returned 2: make PG_CONFIG=/usr/local/bin/pg_config all
```

**Comment by JerrySievert** [comment] 2017-09-19 17:18
the `pgxn` install method requires that you have the pre-requisites installed, in this case a compatible shared library version of `v8` (v5.8+ works well) already installed.  some distributions have compatible versions, some do not (ubuntu, for instance, is only as high as 3.14, which is not compatible)

**Comment by cupuyc** [comment] 2017-09-20 06:52
Thanks for the reply. It looks like I was able to pass this step with running `brew install v8` first.
Now I can't register extension in Postgress. But that is a different issue.

**Comment by JerrySievert** [comment] 2017-09-20 17:52
@cupuyc can you run `brew ls v8` and paste the results?  and if you paste the output of trying to load the extension, that would be great as well.

I'm pretty sure I know what's wrong, but want to verify it first.

**Comment by cupuyc** [comment] 2017-09-20 20:00
```
>brew ls v8 
/usr/local/Cellar/v8/5.1.281.47/bin/d8
/usr/local/Cellar/v8/5.1.281.47/bin/mksnapshot
/usr/local/Cellar/v8/5.1.281.47/bin/process
/usr/local/Cellar/v8/5.1.281.47/bin/v8
/usr/local/Cellar/v8/5.1.281.47/include/libplatform/libplatform.h
/usr/local/Cellar/v8/5.1.281.47/include/ (10 files)
/usr/local/Cellar/v8/5.1.281.47/lib/libv8.dylib
/usr/local/Cellar/v8/5.1.281.47/lib/ (11 other files)
```

For info: I was told to use Docker image `clkao/postgres-plv8:9.6-1.5` and now I'm ok.

**Comment by kkzz8888** [comment] 2017-11-13 01:54
I have the same error (even brew ls v8 the same as cupuyc) with Osx 10.13.1, any help is greatly appreciated! I already have a working postgresql 9.6.5 database and really want to figure this out.

**Comment by JerrySievert** [comment] 2017-11-13 21:40
best bet currently is to build and install:

```
$ wget https://github.com/plv8/plv8/archive/v2.1.0.tar.gz
$ tar -xf v2.1.0.tar.gz
$ cd plv8-2.1.0
$ make static
[... wait a while ...]
$ make install
```

after that, you should be set.

**Comment by kkzz8888** [comment] 2017-11-14 02:49
thanks Jerry, it works!!!

**Comment by umairaslamm** [comment] 2017-11-17 19:26
@JerrySievert I am getting the following error, any ideas

$ make static
/Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile.v8
mkdir -p build
cd build; git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
Cloning into 'depot_tools'...
remote: Sending approximately 16.76 MiB ...
remote: Total 24535 (delta 17946), reused 24535 (delta 17946)
Receiving objects: 100% (24535/24535), 16.74 MiB | 3.35 MiB/s, done.
Resolving deltas: 100% (17946/17946), done.
cd build; fetch v8; cd v8; git checkout 5.8.301; gclient sync
  File "/Users/umair/plv8-2.1.0/build/depot_tools/fetch.py", line 65
    print 'Running: %s' % (' '.join(pipes.quote(x) for x in cmd))
                      ^
SyntaxError: invalid syntax
/bin/sh: line 0: cd: v8: No such file or directory
fatal: Not a git repository (or any of the parent directories): .git
Bootstrapping cipd client for mac-amd64 from https://chrome-infra-packages.appspot.com/client?platform=mac-amd64&version=git_revision:d2677a4477e59cb7de00f1fb8a00e96b1aaeb927...
Traceback (most recent call last):
  File "/Users/umair/plv8-2.1.0/build/depot_tools/gclient.py", line 95, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
make[1]: *** [build/v8-git-mirror-5.8.301] Error 1
make: *** [static] Error 2

**Comment by JerrySievert** [comment] 2017-11-17 19:38
What version of python are you running? The v8 build tools seem tied to python 2

**Comment by umairaslamm** [comment] 2017-11-19 15:40
Thanks @JerrySievert  I switched from Python 3.6.1 to Python 2.7.10 and it workded

**Comment by umairaslamm** [comment] 2017-11-19 15:49
@JerrySievert any idea's on why its throwing this error now and failing 

g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8-git-mirror-5.8.301/include -Ibuild/v8-git-mirror-5.8.301 -stdlib=libc++ -std=c++11 -I. -I./ -I/Library/PostgreSQL/9.6/include/postgresql/server -I/Library/PostgreSQL/9.6/include/postgresql/internal -I/opt/local/20151229/include/libxml2  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -fPIC -c -o plv8_param.o plv8_param.cc
echo "extern const unsigned char coffee_script_binary_data[] = {" >coffee-script.cc
(od -txC -v coffee-script.js | \
	sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>coffee-script.cc
echo "0x00};" >>coffee-script.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8-git-mirror-5.8.301/include -Ibuild/v8-git-mirror-5.8.301 -stdlib=libc++ -std=c++11 -I. -I./ -I/Library/PostgreSQL/9.6/include/postgresql/server -I/Library/PostgreSQL/9.6/include/postgresql/internal -I/opt/local/20151229/include/libxml2  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -fPIC -c -o coffee-script.o coffee-script.cc
echo "extern const unsigned char livescript_binary_data[] = {" >livescript.cc
(od -txC -v livescript.js | \
	sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>livescript.cc
echo "0x00};" >>livescript.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8-git-mirror-5.8.301/include -Ibuild/v8-git-mirror-5.8.301 -stdlib=libc++ -std=c++11 -I. -I./ -I/Library/PostgreSQL/9.6/include/postgresql/server -I/Library/PostgreSQL/9.6/include/postgresql/internal -I/opt/local/20151229/include/libxml2  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include -fPIC -c -o livescript.o livescript.cc
g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.7 -arch i386 -arch x86_64 -O2  -bundle -multiply_defined suppress -Wl,-undefined,dynamic_lookup -o plv8.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/Library/PostgreSQL/9.6/lib -L/opt/local/Current/lib -L/opt/local/20151229/lib  -Wl,-dead_strip_dylibs   build/v8-git-mirror-5.8.301/out/native/libv8_base.a build/v8-git-mirror-5.8.301/out/native/libv8_nosnapshot.a build/v8-git-mirror-5.8.301/out/native/libv8_libplatform.a build/v8-git-mirror-5.8.301/out/native/libv8_libbase.a build/v8-git-mirror-5.8.301/out/native/libv8_libsampler.a build/v8-git-mirror-5.8.301/out/native/libicui18n.a build/v8-git-mirror-5.8.301/out/native/libicuuc.a -lv8_libplatform -bundle_loader /Library/PostgreSQL/9.6/bin/postgres -Lbuild/v8-git-mirror-5.8.301/out/native -stdlib=libc++
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk' [-Wmissing-sysroot]
ld: warning: directory not found for option '-L/opt/local/Current/lib'
ld: warning: directory not found for option '-L/opt/local/20151229/lib'
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [plv8.so] Error 1
make: *** [static] Error 2

**Comment by JerrySievert** [comment] 2017-11-19 17:30
wow, that's a pretty old version of osx (10.8 was released over 5 years ago, with 10.13 being the most current).

a lot has changed since then, including how `c++` is linked.  `libstdc++` was deprecated a few versions back in favor of `libc++`.

you *should* be able to change lines 73 and 74 of `Makefile.v8` to use `-stdlib=libstdc++` instead of `-stdlib=libc++`.  unfortunately, I don't have a version of osx nearly that old, so I won't be able to test it, but those were the changes that were required for modern osx.

**Comment by umairaslamm** [comment] 2017-11-20 13:42
@JerrySievert thats really strange as I do have 10.13 on my machine. 
if I do an _ls_ on the following directory 

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs $ ls
total 8
drwxr-xr-x  4 root  wheel   136B Nov  2 12:09 .
drwxr-xr-x  5 root  wheel   170B Oct 20 19:48 ..
drwxr-xr-x  5 root  wheel   170B Nov  2 12:09 MacOSX.sdk
lrwxr-xr-x  1 root  wheel    10B Oct 22 10:40 MacOSX10.13.sdk -> MacOSX.sdk

I am trying to understand why its trying to find MacOSX10.8.sdk
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk' [-Wmissing-sysroot]
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk' [-Wmissing-sysroot]
ld: warning: directory not found for option '-L/opt/local/Current/lib'
ld: warning: directory not found for option '-L/opt/local/20151229/lib'
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [plv8.so] Error 1
make: *** [static] Error 2

**Comment by JerrySievert** [comment] 2017-11-20 14:52
What version of Xcode are you running? And do you have the most recent command line utilities installed for it?

**Comment by umairaslamm** [comment] 2017-11-21 15:57
I have Xcode 9.1 installed. I am not sure about command line utilities so I downloaded _Command_Line_Tools_macOS_10.12_for_Xcode_9.0.1_ and installed it.
![screen shot 2017-11-21 at 10 56 16 am](https://user-images.githubusercontent.com/2917111/33082405-b209afc8-ceaa-11e7-8592-d0008b0738af.png)
still getting the same error as above.

**Comment by umairaslamm** [comment] 2017-11-21 16:47
I have Xcode 9.1 installed. I am not sure about command line utilities so I downloaded _Command_Line_Tools_macOS_10.12_for_Xcode_9.0.1_ and installed it.
![screen shot 2017-11-21 at 10 56 16 am](https://user-images.githubusercontent.com/2917111/33082405-b209afc8-ceaa-11e7-8592-d0008b0738af.png)
still getting the same error as above.

**Comment by umairaslamm** [comment] 2017-11-21 16:48
@JerrySievert thanks for your help. I have installed http://postgresapp.com/ and it has plv8 builtin. That works for me for now.

**Comment by benjie** [comment] 2018-05-13 21:44
I'm running OS X 10.13.4, XCode 9.3.1, v8 (from brew) v5.1.281.47, PostgreSQL (from brew) v10.4; I'm getting the following build issue:

```
        sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>livescript.cc
echo "0x00};" >>livescript.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -Ibuild/v8/include -Ibuild/v8 -stdlib=libc++ -std=c++11 -I. -I./ -I/usr/local/Cellar/postgresql/10.4/include/server -I/usr/local/Cellar/postgresql/10.4/include/internal  -I/usr/local/opt/openssl/include -I/usr/local/opt/readline/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/libxml2  -fPIC -c -o livescript.o livescript.cc
g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -bundle -multiply_defined suppress -o plv8-2.3.3.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -Wl,-dead_strip_dylibs   -Lbuild/v8/out.gn/x64.release/obj -Lbuild/v8/out.gn/x64.release/obj/third_party/icu -lv8_base -lv8_snapshot -lv8_libplatform -lv8_libbase -lv8_libsampler -lv8_libplatform -bundle_loader /usr/local/Cellar/postgresql/10.4/bin/postgres -Lbuild/v8/out.gn/x64.release/obj -stdlib=libc++
Undefined symbols for architecture x86_64:
  "v8::FunctionTemplate::New(v8::Isolate*, void (*)(v8::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, v8::Local<v8::Signature>, int, v8::ConstructorBehavior)", referenced from:
      SetupPlv8Functions(v8::Local<v8::ObjectTemplate>) in plv8_func.o
      plv8_Prepare(v8::FunctionCallbackInfo<v8::Value> const&) in plv8_func.o
      plv8_GetWindowObject(v8::FunctionCallbackInfo<v8::Value> const&) in plv8_func.o
      plv8_PlanCursor(v8::FunctionCallbackInfo<v8::Value> const&) in plv8_func.o
  "v8::Context::New(v8::Isolate*, v8::ExtensionConfiguration*, v8::MaybeLocal<v8::ObjectTemplate>, v8::MaybeLocal<v8::Value>, v8::DeserializeInternalFieldsCallback)", referenced from:
      GetGlobalContext(v8::Persistent<v8::Context, v8::NonCopyablePersistentTraits<v8::Context> >&) in plv8.o
      CompileDialect(char const*, Dialect) in plv8.o
  "v8::platform::CreateDefaultPlatform(int, v8::platform::IdleTaskSupport, v8::platform::InProcessStackDumping, v8::TracingController*)", referenced from:
      __PG_init in plv8.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [plv8-2.3.3.so] Error 1
```

This is from running

```
$ curl -LO https://github.com/plv8/plv8/archive/v2.3.3.tar.gz
$ tar xf v2.3.3.tar.gz
$ cd plv8-2.3.3
$ make
```

But I get the same on the `master` branch of the repo.

I used to be able to install it like this, but seems that doesn't work with the latest Postgres: https://gist.github.com/benjie/5120a175267dfb96adcf1ee2929033a6

Is PG10.4 supported yet? I'm afraid I'm not experienced reading the linker errors to be able to figure out from what library the issue is arising.

**Comment by JerrySievert** [comment] 2018-05-13 21:50
do not use `v8` from brew, it is out of date, suffers from spectre/meltdown issues, and should not be used with plv8 - plv8 will download and compile `v8` 6.4.388.40.

that said, I'm running pg 10.3, and there have been no breaking changes between 10.3 and 10.4 that I've been able to find.

**Comment by JerrySievert** [comment] 2018-05-13 21:52
I opened a PR for plv8 in homebrew, but they are insisting that v8 be their copy of v8.  I'm at an impasse with them at this point.

**Comment by benjie** [comment] 2018-05-13 22:15
Oh man I wasted so much time on this, building different ways over and over (even different versions of v8 from brew...), it turned out to be as simple as\*:

```
brew uninstall v8
make static
make install
```

Thanks for the pointer @JerrySievert!

\* Actually, I then had to `cd /usr/local/lib/postgresql && ln -s plv8-2.3.3.so plv8.so` for some reason

**Comment by JerrySievert** [comment] 2018-05-13 22:34
It might be interesting to look at your plv8.control file (both in /usr/local and I the plv8 build directory) and make sure they have the plv8-2.3.3.so in there.

**Comment by JerrySievert** [comment] 2018-09-20 00:19
closing this, as it won't be added to brew any time in the future.

**Closed by JerrySievert** 2018-09-20 00:19 UTC
